spring:
  application:
    name: user-service
  profiles:
    active: ${ACTIVE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}

server:
  port: 19091

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


openapi:
  service:
    url : http://localhost:19090/user-service