spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  instance:
    initial-status: up
    prefer-ip-address: true
    instance-id: user-service
    non-secure-port: ${SECURE_PORT}
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/${EUREKA_HOST}/

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}

server:
  port: 19091

management:
  endpoints:
    web:
      exposure:
        include: health,info


openapi:
  service:
    url : http://${SERVICE_URL}/user-service