host:
  url: localhost
  db:
    mysql:
      url: localhost
      port: 3312
    redis:
      url: localhost
  kafka:
    url: localhost
    port: 9092
  zipkin:
    url: localhost
  loki:
    url: localhost

database:
  username: root
  password: root
  name: productDB