server:
  port: 19096

spring:
  application:
    name: product-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}/user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

eureka:
  instance:
    initial-status: up
    prefer-ip-address: true
    instance-id: product-service
    non-secure-port: ${SECURE_PORT}
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/${EUREKA_HOST}/

management:
  endpoints:
    web:
      exposure:
        include: health,info
