spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/payment
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
logging:
  level:
    com.netflix.discovery: off