version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql-coupon
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3309:3306"
    volumes:
      - mysql-data-coupon:/var/lib/mysql # 볼륨 이름 변경
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql-data-coupon: # 볼륨 이름 변경

networks:
  default:
    driver: bridge
